spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baechelin?serverTimezone=Asia/Seoul
    username: root
    password: cz_hyy6848

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  profiles:
    include: jwt, oauth2, cors

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

server:
  port: 9000